# Generated by Django 4.1.5 on 2023-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("price", models.PositiveIntegerField(verbose_name="Price")),
                ("active", models.BooleanField(verbose_name="Active")),
            ],
        ),
    ]
